sudo: required

language: java
jdk:
 - openjdk8
 
before_install:
  - chmod +x mvnw
  
script: ./mvnw clean install 

 
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: us-east-2
  app: springboot-gta-alpha
  env: SpringbootGtaAlpha-env
  zip_file: 'build/libs/springboot-gta-alpha-0.0.1-SNAPSHOT.jar'
  bucket_name: elasticbeanstalk-us-east-2-693831461729
  bucket_path: springboot-gta-alpha
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
